# -*- coding: utf-8 -*-
"""test_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16bFapf_L9Uf_jhRiYQsoIgaCJk3wmimO

lessions for basic and lists
"""

# sample first program
print("Enter your info")
name=input("name: ")
age=int(input("age: "))
salary=float(input("salary: "))
height=eval(input("height: "))

print(f"name: {name}\nage: {age}\nsalary: {salary}\nheight: {height}")

#CRUD - Create Read Update Delete
list5=[10,20,30,40,50, True, False, "Devendra"] #create
print(list5) #read
list5.append("prasad") #update
print(list5)
list5.append([1,2,3])
print(list5)
list5.extend([10,11,"dp"])
print(list5)
reverse_list=list5[3:-3]
print("reverse_list",reverse_list)

tuple_list=tuple(list5)
print("tuple",tuple_list)

list_set=[10,20,30,40,50, True, False, "Devendra"] #create
set1=set([1,2,4, "abc"])
set_from_list=set(list_set)
set_from_tuple=set(tuple(list_set))
print("set_base", set1)
print("set_from_list", set_from_list)
print("set_from_tuple", set_from_tuple)

# dictionaries
dict1={
    "name":"Devendra",
    "age": 40,
    "salary": 2929
}
dict2=dict(name="dp", age=40, salary=9292)
print("dict1",dict1,dict1.keys(),dict1.values(), dict1.get("name"))
print("dict2",dict2,dict1.keys(),dict1.values(), dict2.get("name"))
dict1_items=dict1.items()
print("dict1_items",dict1_items)
first, second=[0,1]

"""functions, oops, and file and error handlers"""

cart_value=600
total_value=0
if cart_value>500:
  total_value=cart_value
  print("cart has no delivery fee")
else:
  print("sorry, no additional discount")
  total_value=cart_value+40

print("total cart value", total_value)

vip_user=True
if cart_value>500 and vip_user:
  print("this is vip user, discount is 70%")
else:
  print("not eligible for discount")

"""loops"""

# for, while - iterate over objects, lists and tuples and get something out of collection
def multiplyViaForLoop():
  print("multiplication table -  via nested for loop")
  for i in range(2, 3):
    for j in range(1, 11):
      mul = (i * j)
      is_prime = (mul % 2)
      prime = "prime" if is_prime == 0 else ""
      print(f"{i:2d} * {j:2d} = {mul: 2d} {prime}")
    print(f"end of multiplication table of {i}\n")

  print("while loop test")

def OTPTest(otp=3121):
  max_attempts=3
  counter=0
  while max_attempts>counter:
    user_otp = int(input(f"attempt: {counter+1} of {max_attempts}, enter otp: "))
    if user_otp == otp:
      print("otp verified, login successful")
      break
    else:
      counter+=1
      continue
  if counter>=max_attempts:
    print("login failed, max attempt exhausted")

def greet(fname, lname, **others):
  print(f"hello, {fname} {lname}. You have gift {others} - {others['gifts']} {others['occasion']}")

def greet1(fname, lname):
  print(f"hello, {fname} {lname}")

# keyword base argument & positional argument
greet(lname="prasad", fname="devendra", gifts="gc card", occasion=" Diwali") #keyword args
greet1(lname="prasad", fname="devendra") #keyword args
greet1("raj", "kumar") #positional argument
multiplyViaForLoop()
# OTPTest(3121)
# OTPTest(123)

"""OOPs & other constructs"""

class Person:
  name=""

  def __init__(self, name: str):
    self.name=name

  def showName(self):
    print(f"hi, {self.name}")


class BankAccount(Person):
  __balance=0

  def __init__(self, name=str, openingBalance=int)->None:
    self.name=name #name is from parent Person
    self.__balance=openingBalance
    self.printBalance("opening", openingBalance)
  def deposit(self, amount=float):
    self.__balance+=amount
    self.printBalance("depositing", amount)
    return self
  def withdraw(self, amount=float):
    self.__balance-=amount
    self.printBalance("withdraing", amount)
    return self
  def printBalance(self, operation="", amount=0):
    print(f"{self.name} has balance: {self.__balance}, {operation} - {amount}")
    return self
  def __repr__(self):
    return f"BankAccount({self.name}, balance={self.__balance})"
  def showName(self):
    print(f"hi, {self.name} & balance: {self.__balance}")
    return self

devendra=BankAccount("Devendra Prasad", 100)
devendra.deposit(200).withdraw(50)
print("\n")
vikas=BankAccount("Vikas", 50)
vikas.deposit(10).withdraw(20)
vikas.withdraw(15)
vikas.deposit(205)
vikas.withdraw(15).deposit(200)

"""files and error handling"""

try:
  file = open("sample.txt", "w")
  file.write("hello dp")
  file.writelines(["\nwhat are you", "\ndoing"])
except:
  print("error came")
finally:
  file.close()

try:
  with open("sample1.txt", "w") as f:
    f.write("hello dp")
    f.writelines(["\nwhat are you", "\ndoing"])
except:
  print("error came")
finally:
  print("finally ran")


try:
  with open("sample1.txt", "r") as f:
    contents = f.read()
    print(f"contents of sample1\n{contents}")
except:
  print("error came")
finally:
  print("finally ran")