const chars = {
  hamburger: "☰",
  pointArrow: "➤",
  close: "✖",
  phone: "☏",
  check: "☑",
  cross: "☒",
  coffee: "☕",
  spade: "☘",
  leftFinger: "☜",
  upFinger: "☝",
  rightFinger: "☞",
  downFinger: "☟",
  sun: "☀",
  cloud: "☁",
  umbrella: "☂",
  snowMan: "☃",
  starFilled: "★",
  star: "☆",
  pathology: "☤",
  yang: "☯",
  menu: "☳",
  tick: "✔",
  down: "↓",
  up: "↑",
  left: "←",
  right: "→",
  speek: "☕",
  euro: "€",
};
export default chars;
