import React from "react";
import type {Metadata} from "next";
import "./globals.css";
import GlobalNav from "@/app/_components/globalNav";
import {SofiaPro} from "@/app/font";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${SofiaPro.className} ${SofiaPro.variable} antialiased h-full min-h-full flex flex-col`}>
        <GlobalNav/>
        <div>
            {children}
        </div>
        </body>
        </html>
    );
}
